
[ClassVersion("1.0.0"), FriendlyName("cComputer")] 
class Grani_cComputer : OMI_BaseResource
{
    [key] string Identifier;
    [Read] string Name;
    [Read, Description("Describe Status is in desired state."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [write] string DomainName;
    [write,EmbeddedInstance("MSFT_Credential")] String Credential;
    [write,EmbeddedInstance("MSFT_Credential")] String UnjoinCredential;
    [write] string WorkGroupName;
};


